const $=s=>document.querySelector(s);let currency='USD';const money=(n,c)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c||currency}).format((n||0)/100);
async function api(path){const r=await fetch(path,{headers:{...MosaicAuth.headers}});if(r.status===401){MosaicAuth.expired();throw Error('Signed out')};if(!r.ok)throw Error((await r.json()).error||'Could not load');return r.json()}
async function load(){try{const [s,t,ar,ap,f]=await Promise.all([api('/api/accounting/status').catch(()=>({verification_state:'not_ready',invalidation_reason:'finish accounting setup'})),api('/api/accounting/trial-balance'),api('/api/accounting/aging?as_of=2026-09-17&kind=receivable'),api('/api/accounting/aging?as_of=2026-09-17&kind=payable'),api('/api/accounting/statements?as_of=2026-09-17')]);currency=s.base_currency||'USD';$('#dashboard').hidden=false;loadBills();$('#verify-title').textContent=s.verification_state==='verified'?'Setup checked':'Setup needs attention';$('#verify-copy').textContent=s.verification_state==='verified'?'Your accounting setup is ready.':(s.invalidation_reason?String(s.invalidation_reason).replace(/^finish /i,'Finish ')+' before filing.':'Finish accounting setup before filing.');$('#verify-chip').textContent=s.verification_state==='verified'?'Ready':'Review';$('#verify-chip').className='chip '+(s.verification_state==='verified'?'green':'amber');$('#status').textContent=s.verification_state==='verified'?'Ready':'Review needed';$('#ar').textContent=money(Object.values(ar.buckets).reduce((a,b)=>a+b,0));$('#ap').textContent=money(Object.values(ap.buckets).reduce((a,b)=>a+b,0));$('#tb').textContent=money(t.total_debit_minor)+' = '+money(t.total_credit_minor);$('#pnl').textContent=money(f.net_profit_minor);const assets=f.balance_sheet.filter(x=>x.type==='asset').reduce((a,x)=>a+x.amount_minor,0),owed=f.balance_sheet.filter(x=>x.type==='liability').reduce((a,x)=>a+x.amount_minor,0);$('#bs').textContent=money(assets)+' in assets, '+money(owed)+' owed';}catch(e){$('#verify-title').textContent='Could not load books';$('#verify-copy').textContent=e.message;$('#verify-chip').textContent='Offline';$('#verify-chip').className='chip red'}}
if(MosaicAuth.require()){let x=JSON.parse(localStorage.getItem('mosaicIdentity')||'{}');$('#company').textContent=x.workspace_name||'Your company';$('#authstate').textContent='Books · '+(x.role||'your role');$('#signout').onclick=()=>MosaicAuth.clear();load()}

const esc=s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function statusChip(status,balance){if(status==='voided')return['Voided','red'];if(status==='draft')return['Draft','amber'];if(status==='approved')return['Approved','amber'];return balance>0?['Open','amber']:['Paid','green']}
async function loadBills(){const tb=$('#bills-body');try{const d=await api('/api/accounting/documents?kind=purchase_bill&limit=20');if(!d.documents.length){tb.innerHTML='<tr><td colspan="7">No supplier bills yet. Record one from the Build screen with a photo of the bill.</td></tr>';return}tb.innerHTML='';d.documents.forEach(b=>{const tr=document.createElement('tr');tr.dataset.id=b.id;const [txt,cls]=statusChip(b.status,b.balance_minor);tr.innerHTML='<td><b>'+esc(b.number)+'</b></td><td data-label="Supplier">'+esc(b.party_name||'')+'</td><td data-label="Bill date">'+esc(b.issue_date)+'</td><td data-label="Due">'+esc(b.due_date||'')+'</td><td data-label="Total" class="num">'+money(b.total_minor,b.currency)+'</td><td data-label="Still owed" class="num">'+money(b.balance_minor,b.currency)+'</td><td data-label="Status"><span class="chip '+cls+'">'+txt+'</span></td>';tr.onclick=()=>{location.hash='#bill/'+b.id};tb.appendChild(tr)})}catch(e){tb.innerHTML='<tr><td colspan="7">Could not load bills: '+esc(e.message)+'</td></tr>'}}
async function openBill(id){$('#dashboard').hidden=true;$('#bill-detail').hidden=false;$('#bill-title').textContent='Loading bill…';try{const b=await api('/api/accounting/document?id='+encodeURIComponent(id));$('#bill-title').textContent='Bill '+b.number;$('#bill-sub').textContent=b.memo||'';const [txt,cls]=statusChip(b.status,b.balance_minor);$('#bill-chip').textContent=txt;$('#bill-chip').className='chip '+cls;$('#bill-total').textContent=money(b.total_minor,b.currency);$('#bill-dates').textContent='Billed '+b.issue_date+(b.due_date?' · due '+b.due_date:'');$('#bill-owed').textContent=money(b.balance_minor,b.currency);const paid=b.payments.reduce((a,p)=>a+p.amount_minor,0);$('#bill-paid').textContent=b.payments.length?b.payments.length+' payment'+(b.payments.length===1?'':'s')+' totalling '+money(paid,b.currency):'No payments yet';$('#bill-vendor').textContent=b.party_name||'—';$('#bill-memo').textContent='Amounts in '+b.currency+'.';$('#bill-lines').innerHTML=b.lines.map(l=>'<tr><td>'+esc(l.description)+'</td><td data-label="Qty" class="num">'+esc(l.quantity)+'</td><td data-label="Unit price" class="num">'+money(l.unit_price_minor,b.currency)+'</td><td data-label="Amount" class="num">'+money(l.total_minor,b.currency)+'</td></tr>').join('');const pc=$('#bill-payments');if(b.payments.length){pc.hidden=false;$('#bill-payments-body').innerHTML=b.payments.map(p=>'<tr><td><b>'+esc(p.number)+'</b></td><td data-label="Paid on">'+esc(p.paid_on)+'</td><td data-label="Amount" class="num">'+money(p.amount_minor,b.currency)+'</td></tr>').join('')}else{pc.hidden=true}}catch(e){$('#bill-title').textContent='Could not load this bill';$('#bill-sub').textContent=e.message}}
function routeBill(){const m=(location.hash||'').match(/^#bill\/(.+)$/);if(m){openBill(m[1])}else{$('#bill-detail').hidden=true;$('#dashboard').hidden=false}}
addEventListener('hashchange',routeBill);routeBill();
const onNav=document.querySelector('.rail nav a.on');if(onNav)onNav.scrollIntoView({inline:'center',block:'nearest'});
