const $=s=>document.querySelector(s);let schema,session,current,selected,templateUsed=sessionStorage.mosaicTemplate||null;const identity=JSON.parse(localStorage.getItem('mosaicIdentity')||'{}');if($('#rail-company'))$('#rail-company').textContent=identity.workspace_name||'Your company';
async function api(path,method='GET',body){let r=await fetch(path,{method,headers:{'Content-Type':'application/json',...MosaicAuth.headers},body:body&&JSON.stringify(body)});let j=await r.json();if(r.status===401){MosaicAuth.expired();throw Error('Signed out')};if(!r.ok)throw Error(j.error||'Could not continue');return j}
async function begin(){if(!MosaicAuth.require())return;schema=await api('/api/onboarding/schema');let id=localStorage.mosaicOnboarding;if(id){try{session=await api('/api/onboarding/session?id='+encodeURIComponent(id))}catch(e){localStorage.removeItem('mosaicOnboarding')}}if(!session){session=await api('/api/onboarding/start','POST',{});localStorage.mosaicOnboarding=session.id}$('#connect').hidden=true;render()}
function render(){if(session.status==='ready'||session.status==='needs_review'||session.status==='applied'){showSummary();return}current=schema.questions.find(q=>q.key===session.current_question);let n=schema.questions.indexOf(current);$('#interview').hidden=false;$('#bar').value=(n/schema.questions.length)*100;$('#rail-step').textContent='Question '+(n+1)+' of '+schema.questions.length;if(templateUsed){let answered=Object.keys(session.answers||{}).length,remaining=schema.questions.length-answered;$('#bar').value=(answered/schema.questions.length)*100;$('#rail-step').textContent=templateUsed+' template - '+remaining+' question'+(remaining===1?'':'s')+' left';$('#question-step').hidden=true;let tip=$('.regional-note'),tplMeta=TEMPLATES.find(x=>x.name===templateUsed)||{};if(tip)tip.innerHTML='<b>'+templateUsed+' template.</b> '+(tplMeta.note||'Regional settings are pre-set.')+' You will review everything before it is saved.';let foot=document.querySelector('.interview-rail footer span');if(foot&&tplMeta.foot)foot.textContent=tplMeta.foot;}$('#question-step').textContent=String(n+1).padStart(2,'0')+' / '+String(schema.questions.length).padStart(2,'0');$('#question').textContent=current.text;$('#why').textContent='Why Mosaic asks: '+current.why;$('#examples').textContent=current.examples?'For example: '+current.examples.join(' / '):'';$('#answer').hidden=current.type==='choice'||current.type==='multi';$('#answer').value='';selected=current.type==='multi'?[]:null;$('#options').innerHTML='';(current.options||[]).forEach(o=>{let b=document.createElement('button');b.textContent=o;b.onclick=()=>{if(current.type==='multi'){selected.includes(o)?selected.splice(selected.indexOf(o),1):selected.push(o);b.classList.toggle('selected',selected.includes(o))}else{selected=o;[...$('#options').children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}};$('#options').appendChild(b)})}
async function save(){let value=current.type==='text'?$('#answer').value:selected;if(!value||(Array.isArray(value)&&!value.length)){ $('#saved').textContent='Please answer in the way that fits your business.';return}session=await api('/api/onboarding/answer','POST',{id:session.id,key:current.key,value});$('#saved').textContent='Saved';render()}
function rail(step){let li=document.querySelectorAll('.rail-progress li');li[1].className=step>=2?'done':'on';li[1].querySelector('i').textContent=step>=2?'\u2713':'2';li[2].className=step>=3?'done':(step===2?'on':'');li[2].querySelector('i').textContent=step>=3?'\u2713':'3'}
function showApplied(){rail(3);let bar=document.querySelector('#summary .card-bar span');if(bar)bar.textContent='LIVE';let note=document.querySelector('.summary-note');if(note)note.textContent='Your Mosaic is ready. The setup you reviewed is now live in your workspace.';let acts=document.querySelector('.summary-actions');if(acts)acts.innerHTML='<p id="apply-state"></p><a class="open-workspace" href="/operations">Open your workspace \u2192</a>'}
async function applySetup(){let b=$('#apply');if(!b)return;b.disabled=true;$('#apply-state').textContent='Saving your confirmed settings\u2026';try{for(let k in jevEdits){session=await api('/api/onboarding/answer','POST',{id:session.id,key:k,value:jevEdits[k]})}$('#apply-state').textContent='Applying your setup\u2026';await api('/api/onboarding/apply','POST',{id:session.id});session.status='applied';showApplied()}catch(e){b.disabled=false;$('#apply-state').textContent=e.message}}
function showSummary(){loadJev();$('#interview').hidden=true;$('#summary').hidden=false;rail(session.status==='applied'?3:2);let i=session.inference;$('#review').innerHTML='<b>Business:</b> '+(i.owner_summary.business||'Your business')+'<br><b>First goal:</b> '+(i.owner_summary.first_goal||'Not answered')+'<br><b>Why features are enabled:</b><ul>'+i.explanations.map(x=>'<li>'+x.because+'</li>').join('')+'</ul>'+(session.contradictions.length?'<b>One thing to clarify:</b> '+session.contradictions.map(x=>x.message).join(' '):'<b>Ready for owner and professional review.</b>');if(session.status==='applied')showApplied()}
$('#start').onclick=()=>begin().catch(e=>$('#state').textContent=e.message);$('#signout').onclick=()=>MosaicAuth.clear();if(MosaicAuth.token&&localStorage.mosaicOnboarding)begin().catch(e=>$('#state').textContent=e.message);$('#save').onclick=()=>save().catch(e=>$('#saved').textContent=e.message);$('#apply').onclick=()=>applySetup();

let jevEdits={};
const JEV_BADGE={auto_accept:['Matched','ok'],confirm:['Please confirm','warn'],blank_confirm:['Your choice','warn'],non_english:['Check meaning','warn'],empty:['Not answered','mute']};
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
async function loadJev(){jevEdits={};let box=$('#jev-review');if(!box)return;box.hidden=true;let rc=$('#reconfig');if(rc)rc.hidden=session.status!=='applied';let r;try{r=await api('/api/jev/map-interview','POST',{id:session.id})}catch(e){return}if(!r.proposals||!r.proposals.length)return;box.hidden=false;$('#jev-counts').textContent=r.auto_accepted+' matched \u00b7 '+r.needs_confirm+' to confirm';let rows=$('#jev-rows');rows.innerHTML='';r.proposals.forEach(p=>{let b=JEV_BADGE[p.status]||['','mute'];let div=document.createElement('div');div.className='jev-row jev-'+p.status;let control;if(p.status==='empty'){control='<span class="jev-none">Not answered</span>'}else if(p.probabilities){let opts=Object.keys(p.probabilities);control='<select data-key="'+p.key+'">'+opts.map(o=>'<option '+(o===p.proposed?'selected':'')+'>'+esc(o)+'</option>').join('')+'</select>'}else{control='<input data-key="'+p.key+'" value="'+esc(p.proposed)+'">'}div.innerHTML='<div class="jev-raw"><span>'+esc(p.ask)+'</span><q>'+esc(p.raw)+'</q></div><div class="jev-arrow">\u2192</div><div class="jev-mapped">'+control+'<em>'+esc(p.reason||'')+'</em></div><span class="jev-badge '+b[1]+'">'+b[0]+'</span>';rows.appendChild(div)});rows.querySelectorAll('select,input').forEach(el=>{el.onchange=()=>{let k=el.dataset.key;let row=el.closest('.jev-row');let badge=row.querySelector('.jev-badge');if(el.value&&el.value!==row.querySelector('q').textContent){jevEdits[k]=el.value;badge.textContent='Edited';badge.className='jev-badge ok'}else{delete jevEdits[k]}}})}
async function reconfigGo(){let t=$('#reconfig-text').value.trim();if(!t)return;$('#reconfig-state').textContent='Thinking\u2026';$('#reconfig-rows').innerHTML='';let r;try{r=await api('/api/jev/reconfigure','POST',{request:t})}catch(e){$('#reconfig-state').textContent=e.message;return}if(r.error==='non_english'){$('#reconfig-state').textContent=r.message;return}if(!r.changes.length){$('#reconfig-state').textContent='No clear setting change in that - try a little more detail.';return}$('#reconfig-state').textContent='';let box=$('#reconfig-rows');r.changes.forEach((c,i)=>{let div=document.createElement('div');div.className='jev-row jev-'+c.status;div.innerHTML='<label class="reconfig-check"><input type="checkbox" data-i="'+i+'" '+(c.status==='auto_accept'?'checked':'')+'></label><div class="jev-raw"><span>'+esc(c.ask||c.target)+'</span><q>'+esc(c.current)+'</q></div><div class="jev-arrow">\u2192</div><div class="jev-mapped"><b>'+esc(c.proposed)+'</b><em>'+esc(c.because)+'</em></div><span class="jev-badge '+(c.status==='auto_accept'?'ok':'warn')+'">'+(c.status==='auto_accept'?'Matched':'Please confirm')+'</span>';box.appendChild(div)});let apply=document.createElement('button');apply.textContent='Apply confirmed changes';apply.className='reconfig-apply';apply.onclick=()=>reconfigApply(r.changes);box.appendChild(apply)}
async function reconfigApply(changes){let picked=[...document.querySelectorAll('#reconfig-rows input[type=checkbox]:checked')].map(el=>changes[+el.dataset.i]);if(!picked.length)return;$('#reconfig-state').textContent='Applying\u2026';try{await api('/api/jev/reconfigure/apply','POST',{changes:picked});$('#reconfig-state').textContent='Done - your Mosaic now matches the change.';$('#reconfig-rows').innerHTML='';$('#reconfig-text').value=''}catch(e){$('#reconfig-state').textContent=e.message}}
if($('#reconfig-go'))$('#reconfig-go').onclick=()=>reconfigGo();

const TEMPLATES=[
{group:'India',id:'kirana',name:'Kirana store',region:'India · INR · GST-ready',note:'INR and GST settings are pre-set.',foot:'India · INR',blurb:'Neighbourhood grocery with khata credit for regulars',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers pick items from the shelves, we weigh or scan them at the counter, they pay by UPI, card or cash.',
 buying:'I buy from local wholesalers and distributor salesmen, check every delivery against the bill, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the bill.',
 staff:'Two helpers run the counter and refill shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'India',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Customer credit entries (khata) and partial supplier deliveries cause the most confusion.',
 brand_style:'Warm and welcoming',brand_colors:'Warm yellow and green',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the khata and stock straight without the evening paper tally.'}},
{group:'India',id:'pharmacy',name:'Pharmacy',region:'India · INR · GST-ready',note:'INR and GST settings are pre-set.',foot:'India · INR',blurb:'Chemist shop with batch and expiry tracking',answers:{
 vertical:'Pharmacy or health',locations:'One place',
 selling:'Customers bring prescriptions or ask for common medicines; we bill at the counter by batch, they pay by UPI, card or cash.',
 buying:'I order from two or three medicine distributors and check batches and expiry on delivery against the bill.',
 stock_pain:'Expiry or batches',credit_behavior:'Only suppliers give us credit',
 discounts:'The printed standard discount on medicines; anything more needs the owner.',
 returns:'Unopened medicines can be returned within a few days with the bill; no returns on opened strips.',
 staff:'One pharmacist handles sales and batches. The owner manages purchasing and supplier payments.',
 money_view:['Sales','Low stock','Money I owe suppliers'],
 country:'India',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Medicines and health products that need batch and expiry tracking.',
 existing_records:'Spreadsheets',
 exceptions:'Expired stock sent back to distributors and short-expiry deliveries cause the most confusion.',
 brand_style:'Clean and professional',brand_colors:'White and medical green',logo:'No, use the business name for now',
 screen_preference:'Stock needing attention',
 goal:'Never sell an expired strip and know what to reorder each morning.'}},
{group:'India',id:'apparel',name:'Apparel shop',region:'India · INR · GST-ready',note:'INR and GST settings are pre-set.',foot:'India · INR',blurb:'Clothing store with seasonal buying and size exchanges',answers:{
 vertical:'Clothing or footwear',locations:'One place',
 selling:'Customers browse and try items, we bill at the counter, they pay by UPI, card or cash.',
 buying:'I buy from wholesale markets and brand distributors before each season and check deliveries against the bill.',
 stock_pain:'Buying too much',credit_behavior:'Only suppliers give us credit',
 discounts:'Season-end sale discounts are set by the owner. Refunds always need the owner.',
 returns:'We exchange within seven days with the bill; sale items are exchange-only.',
 staff:'Two sales staff help customers and manage the floor. The owner manages buying and pricing.',
 money_view:['Sales','Low stock','Profit'],
 country:'India',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Clothing and footwear; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Size exchanges and season-end leftover stock cause the most confusion.',
 brand_style:'Bold and energetic',brand_colors:'Deep maroon and cream',logo:'No, use the business name for now',
 screen_preference:'Start selling',
 goal:'Know which sizes and styles to reorder before the season turns.'}},{group:'Southeast Asia',id:'warung',name:'Warung kiosk',region:'Indonesia · IDR · PPN-ready',note:'IDR and PPN settings are pre-set.',foot:'Indonesia · IDR',blurb:'Neighbourhood kiosk with daily essentials and a credit list for regulars',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers pick items from the shelves or ask at the counter, they pay by cash or QRIS.',
 buying:'I buy from the grosir wholesaler and distributor salesmen, check every delivery against the bill, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Indonesia',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Customer credit entries (the bon list) and partial supplier deliveries cause the most confusion.',
 brand_style:'Warm and welcoming',brand_colors:'Warm yellow and green',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit list and stock straight without the evening paper tally.'}},
{group:'Southeast Asia',id:'sarisari',name:'Sari-sari store',region:'Philippines · PHP · VAT-ready',note:'PHP and VAT settings are pre-set.',foot:'Philippines · PHP',blurb:'Sari-sari convenience store with sachet pricing and a customer utang list',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers buy small everyday items and sachets at the window or counter, they pay by cash or GCash.',
 buying:'I buy from the wholesale grocery and distributor salesmen, check every delivery against the invoice, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One family member helps at the counter. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Philippines',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Customer credit entries (the utang list) and partial supplier deliveries cause the most confusion.',
 brand_style:'Warm and welcoming',brand_colors:'Warm yellow and blue',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the utang list and stock straight without the evening paper tally.'}},
{group:'Southeast Asia',id:'taphoa',name:'Tap hoa grocery',region:'Vietnam · VND · VAT-ready',note:'VND and VAT settings are pre-set.',foot:'Vietnam · VND',blurb:'Family grocery with daily staples and a credit notebook for regulars',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers pick items from the shelves or ask at the counter, they pay by cash or bank transfer QR.',
 buying:'I buy from the wholesale market and distributor salesmen, check every delivery against the bill, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Vietnam',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Customer credit notebook entries and partial supplier deliveries cause the most confusion.',
 brand_style:'Warm and welcoming',brand_colors:'Warm red and yellow',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit notebook and stock straight without the evening paper tally.'}},
{group:'Southeast Asia',id:'kedai',name:'Kedai runcit',region:'Malaysia · MYR · SST-ready',note:'MYR and SST settings are pre-set.',foot:'Malaysia · MYR',blurb:'Neighbourhood provision shop with daily essentials and a credit book',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers pick items from the shelves, we total them at the counter, they pay by cash or DuitNow QR.',
 buying:'I buy from local wholesalers and distributor salesmen, check every delivery against the bill, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Malaysia',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Customer credit book entries and partial supplier deliveries cause the most confusion.',
 brand_style:'Warm and welcoming',brand_colors:'Warm yellow and green',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit book and stock straight without the evening paper tally.'}},
{group:'Southeast Asia',id:'shophouse',name:'Thai shophouse store',region:'Thailand · THB · VAT-ready',note:'THB and VAT settings are pre-set.',foot:'Thailand · THB',blurb:'Shophouse grocery with daily staples and a credit list for regulars',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers pick items from the shelves or ask at the counter, they pay by cash or PromptPay.',
 buying:'I buy from the wholesale market and distributor salesmen, check every delivery against the bill, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Thailand',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Customer credit list entries and partial supplier deliveries cause the most confusion.',
 brand_style:'Warm and welcoming',brand_colors:'Warm red and gold',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit list and stock straight without the evening paper tally.'}},
{group:'Southeast Asia',id:'provision',name:'Provision shop',region:'Singapore · SGD · GST-ready',note:'SGD and GST settings are pre-set.',foot:'Singapore · SGD',blurb:'Heartland provision shop with daily essentials and card and PayNow payments',answers:{
 vertical:'Groceries or food',locations:'One place',
 selling:'Customers pick items from the shelves, we scan them at the counter, they pay by PayNow, card or cash.',
 buying:'I buy from local wholesalers and distributor salesmen, check every delivery against the invoice, and reorder when stock runs low.',
 stock_pain:'Running out',credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'Singapore',
 selling_locations:['Near my registered business'],buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Spreadsheets',
 exceptions:'Supplier deliveries with missing items cause the most confusion.',
 brand_style:'Clean and professional',brand_colors:'Green and white',logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Know what to reorder each morning and keep supplier bills matched.'}},
{group:'East Asia',id:'bianli',name:'Bianli convenience store',region:'China · CNY · VAT-ready',note:'CNY and VAT settings are pre-set.',foot:'China · CNY',blurb:'Community bianli store with daily essentials and mobile payments',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves, we scan them at the counter, they pay by WeChat Pay, Alipay or cash.',
 buying:'I buy from local wholesalers and distributor salesmen, check every delivery against the invoice, and reorder when stock runs low.',
 stock_pain:'Running out',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'China',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Spreadsheets',
 exceptions:'WeChat Pay and Alipay daily totals must match the till at close.',
 brand_style:'Clean and professional',
 brand_colors:'Red and gold',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep mobile-payment totals and stock straight without the evening tally.'}},
{group:'East Asia',id:'konbini',name:'Konbini corner store',region:'Japan · JPY · Consumption-tax-ready',note:'JPY and consumption tax settings are pre-set.',foot:'Japan · JPY',blurb:'Compact convenience store with bento, drinks and daily essentials',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick bento, drinks and daily items, we scan at the register, they pay by cash, IC card or QR code.',
 buying:'Fresh bento and drinks arrive from the distributor twice a day; dry goods come from two wholesalers against delivery notes.',
 stock_pain:'Expiry or batches',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'Japan',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Spreadsheets',
 exceptions:'Fresh food expires the same day and unsold bento is wasted stock.',
 brand_style:'Clean and professional',
 brand_colors:'White and red',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Cut fresh-food waste and know what to reorder each evening.'}},
{group:'East Asia',id:'dongnemart',name:'Dongne mart',region:'South Korea · KRW · VAT-ready',note:'KRW and VAT settings are pre-set.',foot:'South Korea · KRW',blurb:'Neighbourhood mart with daily staples, ramyeon and a credit list for regulars',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves, we scan them at the counter, they pay by card or cash.',
 buying:'Daily deliveries come from two local wholesalers; I check each delivery against the bill.',
 stock_pain:'Running out',
 credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'South Korea',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'The regulars credit list and partial supplier deliveries cause the most confusion.',
 brand_style:'Clean and professional',
 brand_colors:'Blue and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Know what to reorder each morning without the paper tally.'}},
{group:'Middle East',id:'baqqala',name:'Baqqala store',region:'UAE · AED · VAT-ready',note:'AED and VAT settings are pre-set.',foot:'UAE · AED',blurb:'Corner baqqala with daily essentials and monthly accounts for regulars',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves or ask at the counter, they pay by card or cash, and regulars take items on a monthly account.',
 buying:'I buy from the wholesale market and distributor salesmen, check every delivery against the bill.',
 stock_pain:'Running out',
 credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'UAE',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Monthly credit accounts for regulars cause the most confusion.',
 brand_style:'Clean and professional',
 brand_colors:'Green and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the monthly accounts and stock straight without the evening paper tally.'}},
{group:'Middle East',id:'baqala',name:'Baqala grocery',region:'Saudi Arabia · SAR · VAT-ready',note:'SAR and VAT settings are pre-set.',foot:'Saudi Arabia · SAR',blurb:'Neighbourhood baqala with daily staples and a credit notebook',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves, we scan them at the counter, they pay by mada card or cash.',
 buying:'I buy from the wholesale market twice a week and check every delivery against the bill.',
 stock_pain:'Running out',
 credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Saudi Arabia',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'The credit notebook for regulars and partial supplier deliveries cause the most confusion.',
 brand_style:'Clean and professional',
 brand_colors:'Green and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit notebook and stock straight without the evening tally.'}},
{group:'Africa',id:'spaza',name:'Spaza shop',region:'South Africa · ZAR · VAT-ready',note:'ZAR and VAT settings are pre-set.',foot:'South Africa · ZAR',blurb:'Township convenience shop with daily essentials and airtime sales',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers buy daily essentials, airtime and data at the counter, they pay by cash or card, and regulars take items on the book.',
 buying:'I buy from the cash-and-carry wholesaler weekly and check every delivery against the invoice.',
 stock_pain:'Running out',
 credit_behavior:'Only customers use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'South Africa',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Airtime sales and the regulars credit book cause the most confusion.',
 brand_style:'Warm and welcoming',
 brand_colors:'Warm yellow and green',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit book, airtime and stock straight.'}},
{group:'Latin America',id:'mercearia',name:'Mercearia',region:'Brazil · BRL · IBS/CBS-ready',note:'BRL settings are pre-set; Brazil is moving to IBS/CBS - your accountant confirms the transition rules.',foot:'Brazil · BRL',blurb:'Neighbourhood mercearia with daily staples, PIX payments and a fiado book',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves, we weigh or scan them at the counter, they pay by PIX, card or cash, and regulars take fiado.',
 buying:'I buy from the atacado wholesaler weekly and check every delivery against the nota.',
 stock_pain:'Running out',
 credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Brazil',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Fiado credit for regulars and weighed items at the counter cause the most confusion.',
 brand_style:'Warm and welcoming',
 brand_colors:'Green and yellow',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the fiado book and stock straight without the evening tally.'}},
{group:'Latin America',id:'abarrotes',name:'Tienda de abarrotes',region:'Mexico · MXN · IVA-ready',note:'MXN and IVA settings are pre-set.',foot:'Mexico · MXN',blurb:'Corner abarrotes store with daily staples and a fiado list',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves or ask at the counter, they pay by cash or card, and regulars take fiado.',
 buying:'I buy from the central market and distributor salesmen, and check every delivery against the remision.',
 stock_pain:'Running out',
 credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'Mexico',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'The fiado list and weighed items cause the most confusion.',
 brand_style:'Warm and welcoming',
 brand_colors:'Warm red and cream',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the fiado list and stock straight without the evening tally.'}},
{group:'Europe',id:'cornershop',name:'Corner shop',region:'United Kingdom · GBP · VAT-ready',note:'GBP and VAT settings are pre-set.',foot:'United Kingdom · GBP',blurb:'British corner shop with groceries, papers and a card terminal',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick groceries, papers and household items, we scan at the till, they pay by card or cash.',
 buying:'I buy from the cash-and-carry and symbol group deliveries, and check each drop against the invoice.',
 stock_pain:'Running out',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'United Kingdom',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Spreadsheets',
 exceptions:'Newspaper returns and supplier short deliveries cause the most confusion.',
 brand_style:'Clean and professional',
 brand_colors:'Navy and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Know what to reorder each morning and keep supplier invoices matched.'}},
{group:'Europe',id:'kiosk',name:'Kiosk (Büdchen)',region:'European Union · EUR · VAT-ready',note:'EUR and VAT settings are pre-set; rates differ by member state - confirm yours.',foot:'EU · EUR',blurb:'Kiosk with drinks, snacks and everyday essentials',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers buy drinks, snacks and everyday items at the window or counter, they pay by girocard, card or cash.',
 buying:'I buy from the drinks wholesaler and the cash-and-carry, and check deliveries against the Lieferschein.',
 stock_pain:'Running out',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'European Union',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Drinks, snacks and everyday items; bottle deposits are handled at the counter.',
 existing_records:'Paper books',
 exceptions:'Bottle deposit (pfand) returns cause the most confusion.',
 brand_style:'Simple and calm',
 brand_colors:'Yellow and black',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep deposits, stock and the evening cash-up straight.'}},
{group:'North America',id:'bodega',name:'Bodega',region:'United States · USD · Sales-tax-ready',note:'USD settings are pre-set; sales tax rules differ by state and city - confirm yours.',foot:'United States · USD',blurb:'Neighbourhood bodega with daily essentials and a deli counter',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves or order at the deli counter, they pay by card, cash or EBT.',
 buying:'I buy from the cash-and-carry and distributor salesmen, and check every delivery against the invoice.',
 stock_pain:'Running out',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'United States',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is added at checkout',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Deli items sold by weight and EBT-eligible items cause the most confusion.',
 brand_style:'Bold and energetic',
 brand_colors:'Red and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the deli counter, stock and supplier bills straight.'}},
{group:'North America',id:'depanneur',name:'Dépanneur',region:'Canada · CAD · GST/HST-ready',note:'CAD settings are pre-set; GST/HST differs by province - confirm yours.',foot:'Canada · CAD',blurb:'Corner dépanneur with daily essentials, milk and lottery tickets',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick items from the shelves, we scan at the counter, they pay by Interac debit, card or cash.',
 buying:'Milk and bread come daily from the distributor; dry goods come from the cash-and-carry against invoices.',
 stock_pain:'Running out',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'Canada',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is added at checkout',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Spreadsheets',
 exceptions:'Lottery sales and bottle returns cause the most confusion.',
 brand_style:'Clean and professional',
 brand_colors:'Red and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Know what to reorder each morning and keep the lottery till straight.'}},
{group:'Oceania',id:'milkbar',name:'Milk bar',region:'Australia · AUD · GST-ready',note:'AUD and GST settings are pre-set.',foot:'Australia · AUD',blurb:'Suburban milk bar with groceries, drinks and a newspaper rack',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick groceries, drinks and papers, we scan at the counter, they pay by card or cash.',
 buying:'I buy from the cash-and-carry weekly; papers and bread come daily against the invoice.',
 stock_pain:'Running out',
 credit_behavior:'Only suppliers give us credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Low stock','Profit'],
 country:'Australia',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'Newspaper deliveries and the weekend cash-up cause the most confusion.',
 brand_style:'Simple and calm',
 brand_colors:'Blue and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Know what to reorder each morning and keep the weekend cash-up straight.'}},
{group:'Oceania',id:'dairy',name:'Corner dairy',region:'New Zealand · NZD · GST-ready',note:'NZD and GST settings are pre-set.',foot:'New Zealand · NZD',blurb:'Corner dairy with daily essentials, milk, bread and a credit list',answers:{
 vertical:'Groceries or food',
 locations:'One place',
 selling:'Customers pick daily essentials, milk and bread, we scan at the counter, they pay by EFTPOS card or cash.',
 buying:'Milk and bread arrive daily; dry goods come from the cash-and-carry against invoices.',
 stock_pain:'Running out',
 credit_behavior:'Customers and suppliers both use credit',
 discounts:'Regular customers get small discounts at the counter. Refunds always need the owner.',
 returns:'We exchange unopened items within a few days with the receipt.',
 staff:'One helper runs the counter and refills shelves. The owner manages purchasing and prices.',
 money_view:['Sales','Money customers owe','Low stock'],
 country:'New Zealand',
 selling_locations:['Near my registered business'],
 buying_locations:['Nearby suppliers'],
 price_display:'Tax is included in the shown price',
 customer_type:'Households',
 product_tax_facts:'Staple foods and everyday items; no special tax treatment that our accountant flags.',
 existing_records:'Paper books',
 exceptions:'The credit list and daily milk and bread deliveries cause the most confusion.',
 brand_style:'Simple and calm',
 brand_colors:'Black and white',
 logo:'No, use the business name for now',
 screen_preference:'Today’s manager checklist',
 goal:'Keep the credit list and stock straight without the evening tally.'}}];
function renderTemplates(){let sec=$('#templates'),box=$('#template-cards');if(!sec||!box)return;if(localStorage.mosaicOnboarding)return;sec.hidden=false;let groups=[];TEMPLATES.forEach(t=>{let g=groups.find(x=>x.label===t.group);if(!g){g={label:t.group,items:[]};groups.push(g)}g.items.push(t)});let chips=document.createElement('div');chips.className='template-chips';box.appendChild(chips);let body=document.createElement('div');box.appendChild(body);function draw(label){body.innerHTML='';groups.filter(g=>label==='All regions'||g.label===label).forEach(g=>{let h=document.createElement('p');h.className='template-group';h.textContent=g.label;body.appendChild(h);let grid=document.createElement('div');grid.className='template-cards';g.items.forEach(t=>{let b=document.createElement('button');b.type='button';b.className='template-card';b.innerHTML='<b>'+t.name+'</b><span class="template-region">'+t.region+'</span><small>'+t.blurb+'</small>';b.onclick=()=>startTemplate(t).catch(e=>{$('#state').textContent=e.message});grid.appendChild(b)});body.appendChild(grid)});[...chips.children].forEach(c=>c.classList.toggle('on',c.textContent===label))}['All regions'].concat(groups.map(g=>g.label)).forEach(label=>{let c=document.createElement('button');c.type='button';c.className='template-chip';c.textContent=label;c.onclick=()=>draw(label);chips.appendChild(c)});draw('All regions')}
async function startTemplate(t){templateUsed=t.name;sessionStorage.mosaicTemplate=t.name;$('#state').textContent='Starting from the '+t.name+' template - pre-filling typical answers…';await begin();for(const [k,v] of Object.entries(t.answers)){session=await api('/api/onboarding/answer','POST',{id:session.id,key:k,value:v})}$('#state').textContent='Template answers pre-filled. Tell Mosaic your shop’s name, then review everything before it goes live.';render()}
renderTemplates();
