let qs=[],a={},multi=[],ready=false,cfg=null,draft=null,pendingChange=null,ws=JSON.parse(localStorage.getItem('mosaic-workspace')||'null'),toastTimer=null;
function toast(msg,action,fn,spin){clearTimeout(toastTimer);let t=$('#toast');t.innerHTML=(spin?'<span class="spin"></span>':'')+'<span>'+esc(msg)+'</span>'+(action?'<button>'+esc(action)+'</button>':'');t.style.display='flex';if(action){t.querySelector('button').onclick=()=>{t.style.display='none';fn()}}else{toastTimer=setTimeout(()=>t.style.display='none',3600)}}
async function api(path,body){let err;for(let i=0;i<3;i++){try{let c=new AbortController(),t=setTimeout(()=>c.abort(),9000),r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal});clearTimeout(t);if(r.status===401){MosaicAuth.expired();throw new Error('Signed out')}if(!r.ok)throw new Error('HTTP '+r.status);return r}catch(e){err=e;if(i<2){toast('Connection problem - retrying… ('+(i+1)+'/3)',null,null,true);await new Promise(r=>setTimeout(r,500*Math.pow(2,i)))}}}throw err}
function guard(p){p.catch(()=>toast('Could not reach the server. Your answers are safe on this device.','Try again',()=>location.reload()))}
function setSync(state,cls){let el=$('#syncstate');el.textContent=state;el.className='syncstate '+(cls||'')}
async function wsGet(){let r=await fetch('/api/workspace/config',{headers:{Authorization:'Bearer '+ws.key}});if(r.status===404)return null;if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function syncPush(summary){if(!ws||!cfg)return;setSync('Saving online…');try{let cur=await wsGet(),base=cur?cur.version:0,r=await fetch('/api/workspace/config',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:'Bearer '+ws.key,'Idempotency-Key':'ui-'+ws.wid+'-v'+(base+1)},body:JSON.stringify({answers:a,config:stripCfg(cfg),base_version:base,summary:summary||'Saved from studio'})});if(!r.ok)throw new Error('HTTP '+r.status);let d=await r.json();setSync('Saved online','ok')}catch(e){setSync('Save failed - tap Save online','bad');toast('Could not save online. Your work is safe on this device.','Try again',()=>syncPush(summary))}}
function stripCfg(c){let x={};for(let k in c){if(k!=='export')x[k]=c[k]}return x}
async function syncStart(){if(ws)return syncPush('Manual save');setSync('Saving online…');try{let r=await fetch('/api/workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:(cfg&&cfg.business)||'Mosaic workspace'})});if(!r.ok)throw new Error('HTTP '+r.status);let d=await r.json();ws={wid:d.workspace_id,key:d.api_key};localStorage.setItem('mosaic-workspace',JSON.stringify(ws));toast('Online backup is on. Your work now saves automatically.');syncPush('First save')}catch(e){setSync('Save failed - tap Save online','bad');toast('Could not start online backup.','Try again',syncStart)}}
async function syncRestore(){setSync('Checking online save…');try{let srv=await wsGet();if(!srv){setSync('Saved on this device');return}if(!cfg){cfg=srv.config;a=srv.answers;ready=!!cfg.ready;await refetchQuestions();render(cfg);if(ready){$('#state').textContent='BLUEPRINT READY';$('#answer').placeholder='Ask to view or change tax settings…'}toast('Restored your saved business from online backup.')}else{syncPush('Opened')}setSync('Saved online','ok')}catch(e){setSync('Working offline','bad');toast('No connection to online backup. You can keep working - everything stays on this device.','Try again',syncRestore)}}
window.addEventListener('offline',()=>setSync('No internet','bad'));window.addEventListener('online',()=>{if(ws)syncPush('Reconnect')});const $=s=>document.querySelector(s),esc=s=>{let d=document.createElement('div');d.textContent=s;return d.innerHTML},say=(x,c='agent')=>{$('#messages').insertAdjacentHTML('beforeend',`<div class="msg ${c}">${esc(x)}</div>`);$('#messages').scrollTop=99999};
async function refetchQuestions(){let r=await api('/api/questions',{answers:a});qs=(await r.json()).questions}
async function preview(){let r=await api('/api/preview',a);render(await r.json())}
function render(d){document.documentElement.style.setProperty('--accent',d.accent);$('#erpname').textContent=d.business+' ERP';$('#welcome').textContent=d.business==='Your business'?'Good morning':'Good morning, '+d.business;$('#terms').textContent=`${d.terminology.items} · ${d.terminology.sales} · ${d.terminology.customers} · tracked by ${d.terminology.stock_unit}`;$('#navitems').innerHTML=d.navigation.map(x=>`<div class="navitem">${esc(x)}</div>`).join('');let sym=(d.currency&&d.currency.symbol)||'₹';$('#kpis').innerHTML=d.kpis.map((x,j)=>`<div class="kpi"><small>${esc(x)}</small><b>${j==0?esc(sym)+'—':'—'}</b></div>`).join('');$('#modules').innerHTML=d.modules.slice(0,12).map(x=>`<div class="card module"><i>${esc(x.icon)}</i><b>${esc(x.name)}</b><small>${esc(x.why)}</small></div>`).join('');$('#modulecount').textContent=d.modules.length+' active';let t=d.tax,wrap=$('#taxwrap');if(t){wrap.style.display='block';$('#taxtitle').textContent=t.tax_name+' profile';$('#taxtag').textContent=t.jurisdiction+(t.subdivision?' · '+t.subdivision:'')+' · '+t.registration.type;let rows=[['Registration',t.registration.type],['Identity',t.registration.label],['Threshold',t.registration.threshold],['Invoice',t.invoice[0]],['Credits',t.credits],['Authority',t.authority]];let chips=[...t.rules,...t.returns];let rates=t.rates.slabs.map(x=>x.band+' '+x.rate+'%').join(' · ');$('#taxpanel').innerHTML='<div class="ggrid">'+rows.map(r=>'<div><small>'+esc(r[0])+'</small><b>'+esc(r[1])+'</b></div>').join('')+'</div><div class="gline">'+esc(t.rates.structure)+(rates?' — '+esc(rates):'')+'</div><div>'+chips.map(c=>'<span class="role">'+esc(c)+'</span>').join('')+'</div>'+t.validations.map(v=>'<div class="gnote">✓ '+esc(v.check)+': '+esc(v.status)+'</div>').join('')+t.warnings.map(w=>'<div class="gwarn">⚠ '+esc(w)+'</div>').join('')+'<div class="gsrc">'+t.sources.map(s=>esc(s.title)).join(' · ')+' — verified '+esc(t.effective)+'</div>'}else wrap.style.display='none';$('#flows').innerHTML=d.workflows.slice(0,7).map(x=>`<div class="flow">${esc(x)}</div>`).join('');$('#roles').innerHTML=d.roles.map(x=>`<span class="role">${esc(x)}</span>`).join('');$('#erp').classList.remove('pulse');void $('#erp').offsetWidth;$('#erp').classList.add('pulse')}
function ask(){let i=qs.findIndex(q=>!(q.key in a));$('#prog').style.width=(Object.keys(a).length/Math.max(qs.length,1)*100)+'%';if(i<0)return finish();let q=qs[i];say(q.text);$('#choices').innerHTML='';multi=[];if(q.type==='text'){$('#entry').style.display='flex';$('#answer').placeholder=q.placeholder||'Type your answer…';$('#answer').focus()}else{$('#entry').style.display=q.type==='multi'?'flex':'none';q.options.forEach(o=>$('#choices').insertAdjacentHTML('beforeend',`<button>${esc(o)}</button>`));[...$('#choices').children].forEach(b=>b.onclick=()=>{if(q.type==='choice')submit(b.textContent);else{b.classList.toggle('on');multi=[...$('#choices .on')].map(x=>x.textContent)}})}}
async function submit(v){if(!v||(Array.isArray(v)&&!v.length))return;say(Array.isArray(v)?v.join(', '):v,'user');let q=qs.find(x=>!(x.key in a));if(q)a[q.key]=v;$('#answer').value='';await refetchQuestions();await preview();if(qs.every(x=>x.key in a))guard(finish());else setTimeout(ask,180)}
async function finish(){say('Your custom ERP blueprint is ready. You can now change tax and compliance settings right here - try "show my tax settings", "change registration to composition", or "export my tax configuration".');$('#entry').style.display='flex';$('#choices').innerHTML='';$('#answer').placeholder='Ask to view or change tax settings…';$('#prog').style.width='100%';$('#state').textContent='BLUEPRINT READY';let r=await api('/api/configure',a);cfg=await r.json();ready=true;localStorage.setItem('mosaic-blueprint',JSON.stringify(cfg));render(cfg);syncPush('Onboarding blueprint')}
async function sendChat(text){say(text,'user');$('#answer').value='';let body={answers:a,config:cfg,message:text};if(draft)body.draft=draft;if(pendingChange)body.pending=pendingChange;let r=await api('/api/chat',body),d=await r.json();say(d.reply);$('#choices').innerHTML='';if(d.intent==='preview'){pendingChange=d.preview;draft=null;['Apply change','Cancel'].forEach(x=>$('#choices').insertAdjacentHTML('beforeend',`<button>${x}</button>`));let[k,c]=$('#choices').children;k.onclick=()=>sendChat('apply');c.onclick=()=>{pendingChange=null;sendChat('cancel')}}else if(d.intent==='collect'){draft=d.draft}else{if(d.intent==='applied'||d.intent==='rollback'){cfg=d.config;a=cfg.answers||a;localStorage.setItem('mosaic-blueprint',JSON.stringify(cfg));render(cfg);syncPush(d.intent==='applied'?'Applied chat change':'Rollback')}if(d.intent==='export'){let b=new Blob([JSON.stringify(d.export,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),l=document.createElement('a');l.href=u;l.download='mosaic-erp-config.json';l.click();URL.revokeObjectURL(u)}pendingChange=null;if(d.intent==='refuse')draft=d.draft||draft}}
$('#syncbtn').onclick=syncStart;$('#send').onclick=()=>{let v=ready?$('#answer').value.trim():(qs.find(x=>!(x.key in a))?.type==='multi'?multi:$('#answer').value.trim());ready?guard(sendChat(v)):guard(submit(v))};$('#answer').onkeydown=e=>{if(e.key==='Enter')$('#send').click()};
$('#exportbtn').onclick=()=>guard((async()=>{let r=await api('/api/export',a),b=await r.blob(),u=URL.createObjectURL(b),l=document.createElement('a');l.href=u;l.download='mosaic-erp-config.json';l.click();URL.revokeObjectURL(u)})());
(async()=>{if(ws)await syncRestore();let saved=localStorage.getItem('mosaic-blueprint');if(saved){cfg=JSON.parse(saved);a=cfg.answers||{};await refetchQuestions();render(cfg);if(cfg.ready){ready=true;$('#state').textContent='BLUEPRINT READY';$('#answer').placeholder='Ask to view or change tax settings…';say('Welcome back. Your blueprint is loaded - ask me to view or change tax settings anytime.')}else ask()}else{await refetchQuestions();preview();ask()}})();
